### ISSUE TITLE
Text components API

### ISSUE THREAD

**Issue by feature** [staminadevelopment/minecraft-api#19]
Add an API for interacting with text components. Text components are what Minecraft uses for chat, among a few other things. The goal of the API is not to cover the whole text components system, but just the most common set of features. The API must focus on maximizing version compatibility between 1.8.9 and the newest versions, the API must also provide a DSL-like syntax for creating text components.

**Comment by voidstar0** [comment]
When you say interacting with text components does this cover both the creation and deserialization of text components?

**Comment by feature** [comment]
At the moment (de)serialization is not planned to be part of the API. However that doesn't necessarily mean that it won't be added. I'm unsure if it will be added in the initial PR, later, or maybe never.
